config/routes.rb
MiBlog::Application.routes.draw do

  

  root :to => "posts#index"

  get  'create'  => "posts#create", :as => "public_post"

  resources :posts do # Define route for post
    resources :comments  #Define route for post/comments
    get 'last/:num' => "posts#last", :on => :collection, :as => :last
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  attr_accessible :author, :content, :post, :post_id
  belongs_to :post
  validates :author, :content, :presence => true

end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :content, :title, :comments, :author
  validates :title, :content, :author, :presence => true

  has_many :comments

  scope :newer_posts, lambda { |num| order("created_at DESC").limit(num) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])

    respond_to do |format|
        if @comment.save
          format.html {
            flash[:success] = "Comment created successfully."
            redirect_to @post
          }
          format.js
        else
          format.html {
            flash[:error] = "Comment needs an author and content."
            render 'posts/show'
          }
        end
    end

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.to_a
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      flash[:success] = "Post created successfully."
      redirect_to root_path
    else
      render 'posts/create'
      flash[:error] = "Post title, content and author are required."
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(:post_id => @post.id)

    rescue ActiveRecord::RecordNotFound
    flash[:error] = "The post doesn't exist."
    redirect_to root_path
  end

  def last
    @posts = Post.newer_posts(params[:num])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
%li.well{:id => "comment-#{comment.id}"}
  %cite
    = comment.author
    says:
  .comment_text
    = comment.content

app/views/comments/_form.html.haml
= form_for [@post, @comment] do |f|
  %p
    = f.label :author
    = f.text_field :author
  %p
    = f.label :content
    = f.text_area :content
  = f.submit "Public comment"

app/views/comments/create.js.haml
$("#comments_list").append("#{escape_javascript(render(:partial => @comment))}");

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Posts"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/posts"} Main Posts
          .container.nav-collapse
            %ul.nav
          / /.nav-collapse
    .container
      .row
        .span9
          %br/
          %br/
          %br/
          - flash.each do |key, value|
            %div{:class => "flash alert alert-#{key}"}
              = value
          %h1.post_title Forum Application, public your posts now!!
          %br/
          = yield
        .span3
          %br/
          %br/
          .well.sidebar-nav
            %h2 Options
            %ul.nav.nav-list
              %li.nav-header
              %li= link_to "Public a new post", public_post_path
              %li= link_to "View the last 3 Posts created", last_posts_path(3)
              %li= link_to "View all posts", root_path
          / /.well
        / /span
      / /row
      %footer
        %p &copy; fhantoing 2013
    / /container

app/views/posts/_post.html.haml
.post_content_border
  %h2.post_title= link_to post.title, post
  .post_content
    = post.content
%br/

app/views/posts/create.html.haml
%h3 Public an new Post
= form_for @post do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :content
    = f.text_area :content
  %p
    = f.label :author
    = f.text_field :author
  = f.submit "Public post"

app/views/posts/index.html.haml
= content_for :title do
  Main - Posts
= render @posts

app/views/posts/last.html.haml
= render @posts

app/views/posts/show.html.haml
= content_for :title do
  = @post.title

.post_content_border
  %h2.post_title= @post.title
  %h6.post_title
    by:#{@post.author}
  .post_content= @post.content

%ol#comments_list= render @post.comments

%br/

%h3.post_title
  Public an new comment

= render 'comments/form'